name: Bug Report
description: File a bug report to help us improve Oat
title: "[BUG]: "
labels: [bug, triage]
assignees: [mrgnhnt96]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us diagnose and fix the issue.

  - type: checkboxes
    attributes:
      label: Bug Report Checklist
      description: |
        Please check the following before submitting your bug report:
      options:
        - label: I have searched the existing issues to ensure this is not a duplicate
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: "1. Do this\n2. Do that\n3. See the bug!"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Oat are you using?
      placeholder: 0.1.0
    validations:
      required: true

  - type: textarea
    id: computer-info
    attributes:
      label: Computer Information
      description: What operating system are you using?
      placeholder: MacOS, Windows, Linux, etc.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Anything else you want to add?
      placeholder: Tell us more!
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue.
      placeholder: Drag and drop screenshots here!
    validations:
      required: false
