name: Feature Request
description: Suggest a new feature or enhancement for Oat
title: "[FEATURE]: "
labels: [enhancement, triage]
assignees: [mrgnhnt96]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand your feature request.

  - type: textarea
    id: what-feature
    attributes:
      label: What feature would you like to see?
      description: Describe the feature you would like to see added to Oat.
      placeholder: Tell us what you want!
      value: "I would like to see..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Oat are you using?
      placeholder: 0.1.0
      value: 0.1.0
    validations:
      required: true

  - type: textarea
    id: computer-info
    attributes:
      label: Computer Information
      description: What operating system are you using?
      placeholder: MacOS, Windows, Linux, etc.
      value: MacOS, Windows, Linux, etc.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: Tell us how you would use this feature!
      value: "I would use this feature to..."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you would like to provide?
      placeholder: Tell us anything else you think we should know!
      value: "I think you should know..."
    validations:
      required: false